### ISSUE TITLE
NGX_ERRORS_DECLARATIONS not working see error below

### ISSUE THREAD

**Issue by juvegitau** [DmitryEfimenko/ngspot#16] opened 2024-06-18 18:51 UTC
[ERROR] TS2322: Type 'readonly [typeof ErrorsDirective, typeof ErrorDirective, typeof NgxErrorsFormDirective]' is not assignable to type 'any[] | Type<any> | ModuleWithProviders<{}>'.
  The type 'readonly [typeof ErrorsDirective, typeof ErrorDirective, typeof NgxErrorsFormDirective]' is 'readonly' and cannot be assigned to the mutable type 'any[]'. [plugin angular-compiler]

    src/app/account/account.module.ts:35:4:
      35 │     NGX_ERRORS_DECLARATIONS,
         ╵     ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by DmitryEfimenko** [comment] 2024-06-19 00:05
Could you please create a reproduction on StackBlitz?

**Comment by DmitryEfimenko** [comment] 2024-06-23 22:44
closing due to no repro available.

**Closed by DmitryEfimenko** 2024-06-23 22:44 UTC

**Comment by nLeichtle** [comment] 2024-10-02 20:07
I was able to reproduce the error.
Removing "readonly" in errors-declarations.d.ts fixed the error for me.

Additionally, the error occurred using NgModules only. Standalone component imports worked fine without any fix.

**Comment by sgameirojr** [comment] 2025-02-03 23:25
This is happening with the package coming from NPM. 
Seems like the code is outdated. Can the NPM package be updated @DmitryEfimenko ?
I can fix this with the local build, but it brakes automated builds.

**Comment by DmitryEfimenko** [comment] 2025-02-03 23:37
Do you think it's just a matter of building the latest code and pushing it to npm or is there a code change required?

**Comment by sgameirojr** [comment] 2025-02-04 00:44
I think some code change is needed.
I've just cloned main and built the package for ngx-errors, and I see that the readonly gets added to the output during the build process.

Seems the "as const" in NGX_ERRORS_DECLARATIONS is what causes that addition. So it would require a code change to errors-declarations.ts.

**Comment by DmitryEfimenko** [comment] 2025-02-04 01:11
I thought that was the recommended by Angular team way of exporting declarations. I can't find this in the docs at the moment though. I can try and publish without it

**Comment by sgameirojr** [comment] 2025-02-04 01:34
Maybe incompatibility with imports in NgModule? :-/
Not sure.

**Comment by DmitryEfimenko** [comment] 2025-02-08 05:31
@sgameirojr, can you please make sure that `NGX_ERRORS_MATERIAL_DECLARATIONS` are imported as the following:
```ts
imports: [
   ...NGX_ERRORS_DECLARATIONS
]
```
... and NOT like this:
```ts
imports: [
   NGX_ERRORS_DECLARATIONS
]
```
Please let me know if that fixes the issue
